name: "CI"
on:
  push:
  pull_request:
jobs:
  tests:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { pkg: librustc_codegen_gcc }
          - { pkg: rx-embedded-librustc_codegen_gcc }
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: nix-rustc-codegen-gcc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # - run: nix build ".#${{ matrix.pkg }}"
    # FIXME: Waiting for <https://github.com/nix-community/naersk/pull/234>
    # FIXME: The default version of Nix Waiting for <https://github.com/NixOS/nix/pull/6582>
    - name: Build Nix
      run: nix build "github:NixOS/nix/027fd45230b74c67e65d06e7073c04b62c60eb4e" -o ./new-nix
    - run: ./new-nix/bin/nix build ".#${{ matrix.pkg }}" --override-input naersk github:yvt/naersk/36ca101a9b183332fa8d70ab05d416949ba1b050
